export const supportedLanguages: { name: string; id: string }[] = [
	{ name: "Batch", id: "bat" },
	{ name: "C", id: "c" },
	{ name: "C++", id: "cpp" },
	{ name: "C#", id: "csharp" },
	{ name: "Clojure", id: "clojure" },
	{ name: "CoffeeScript", id: "coffeescript" },
	{ name: "Compose", id: "dockercompose" },
	{ name: "CSS", id: "css" },
	{ name: "Cuda C++", id: "cuda-cpp" },
	{ name: "Diff", id: "diff" },
	{ name: "Docker", id: "dockerfile" },
	{ name: "F#", id: "fsharp" },
	{ name: "Go", id: "go" },
	{ name: "GraphQL", id: "graphql" },
	{ name: "Groovy", id: "groovy" },
	{ name: "HTML", id: "html" },
	{ name: "Ignore", id: "ignore" },
	{ name: "Ini", id: "ini" },
	{ name: "Java", id: "java" },
	{ name: "JavaScript", id: "javascript" },
	{ name: "JavaScript React", id: "javascriptreact" },
	{ name: "JSON", id: "json" },
	{ name: "JSON Comments", id: "jsonc" },
	{ name: "Julia", id: "julia" },
	{ name: "Less", id: "less" },
	{ name: "Log", id: "log" },
	{ name: "Lua", id: "lua" },
	{ name: "Makefile", id: "makefile" },
	{ name: "Markdown", id: "markdown" },
	{ name: "Objective-C", id: "objective-c" },
	{ name: "Objective-C++", id: "objective-cpp" },
	{ name: "Perl", id: "perl" },
	{ name: "PHP", id: "php" },
	{ name: "Plain Text", id: "plaintext" },
	{ name: "Powershell", id: "powershell" },
	{ name: "Properties", id: "properties" },
	{ name: "Pug", id: "jade" },
	{ name: "Python", id: "python" },
	{ name: "R", id: "r" },
	{ name: "Razor", id: "razor" },
	{ name: "Ruby", id: "ruby" },
	{ name: "Rust", id: "rust" },
	{ name: "SCSS", id: "scss" },
	{ name: "Shell Script", id: "shellscript" },
	{ name: "SQL", id: "sql" },
	{ name: "Swift", id: "swift" },
	{ name: "TypeScript", id: "typescript" },
	{ name: "TypeScript React", id: "typescriptreact" },
	{ name: "Vue", id: "vue" },
	{ name: "XML", id: "xml" },
	{ name: "YAML", id: "yaml" }
];
